Update curl endpoint in OPW testing workflow to check the login page
This change modifies the curl request to target the "/web/login" endpoint instead of the root URL. It ensures the test verifies the accessibility of the login page directly, improving the reliability of the server status check.

diff --git a/.github/workflows/opw-testing.yml b/.github/workflows/opw-testing.yml
--- a/.github/workflows/opw-testing.yml
+++ b/.github/workflows/opw-testing.yml
@@ -48,7 +48,7 @@ jobs:
           count=0
           max_attempts=30
           while true; do
-            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.TESTING_SERVER }}:8069 || echo "Curl failed")
+            status_code=$(curl --write-out "%{http_code}\n" --silent --output /dev/null ${{ vars.TESTING_SERVER }}:8069/web/login || echo "Curl failed")
             if [ "$status_code" = "200" ]; then
               break
             else
